### ISSUE TITLE
Unexpected call to terminal-api-live.adyen.com during rendering of Cart Page

### ISSUE THREAD

**Issue by matei** [Adyen/adyen-magento#1072]
**Magento version**: 2.3.2
**Plugin version**: 4.3.0
**Description**

Noticed on Cart Page traces in New Relic. It seems that the cart page is performing calls to terminal-api-live.adyen.com, as part of Adyen\Service\PosPayment::getConnectedTerminals
We don't expect this to happen (especially on the cart page, and especially since we are not using PosPayment)

**Comment by cyattilakiss** [comment]
Hi @matei ,

Thank you for raising this issue. It has been already fixed in this PR: https://github.com/Adyen/adyen-magento2/pull/515 which was released in the https://github.com/Adyen/adyen-magento2/releases/tag/4.5.0 .
If you have more Magento2 related questions please use our https://github.com/Adyen/adyen-magento2 repository to help us keep the related questions together :)

Best regards and Happy New Year!
Attila
Adyen
