### ISSUE TITLE
failed refund should block saving credit memo

### ISSUE THREAD

**Issue by ebaschiera** [Adyen/adyen-magento#524]
Hi,
situation: I create a credit memo in magento and I choose to make an online refund.
If for some reason the method Adyen_Payment_Model_Adyen_Abstract::sendRefundRequest() receives an empy PSP as argument, credit memo is created successfully, but there is no actual refunds at Adyen. So the user has no feedback about the online refund going wrong. There is just a "oops empty pspReference" message in adyen_notification.log.
IMHO the credit memo should not be saved and the user should get an error.

Thanks!

**Comment by ebaschiera** [comment]
While I was there I thought it was useful to throw an exception also when capturing and canceling... :)

**Comment by rikterbeek** [comment]
Hi Ermanno,

For cancellation we can not do this because an adyen payment could not come through by us because of shopper has left the page. Then you want to cancel the order in magento without our psp reference.
For online refund and online creditmemo yes we could throw an exception instead of this legacy error message. I will look into this.

Regards,
Rik
Adyen

**Comment by questionmark78** [comment]
We noticed that when the feedback of a refund request was added to the notification queue with success = 0 (false) and message 'Operation failed' and the queue is processed, the order get's a status update, but the creditmemo is still successful.
Can you think of a way to alert the admin user of the fact the creditmemo payment failed?
This typically happens when Adyen did a payment to Merchant and the funds are thus insufficient to do a (large) refund. Part of the solution is to have an deposit on the Merchant account always, but there is no way to check for this.

**Comment by rikterbeek** [comment]
Hi questionmark78,

When a refund failed the adyen event status will change to refund : false.
In the comment history you can see as well that the refund was not successful and with a reason why.
Is this not enough for you ?

Regards,
Rik
Adyen

**Comment by questionmark78** [comment]
The issue is that in the workflow there is no reviewing of the order after the queue is processed. And 99% or more of the refunds are no problem, but is not very visible in a workflow if it is not ok.

**Comment by rikterbeek** [comment]
Hi questionmark78,

What would it make it visible in your workflow giving it a special order status ?

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Please let me know if there are some open questions around this issue.

Regards,
Rik
Adyen
