### ISSUE TITLE
Update uses new/different way of changing state?

### ISSUE THREAD

**Issue by mrdevries** [Adyen/adyen-magento#615]
Hi Rik,

Today we upgraded to version 2.6.2 of the extension and stumbled upon the fact it uses a different way of setting the order state to e.g. processing. A fulfilment extension we use (ActiveAnts) listens to an event to check if the order is processing, however the new way doesn't trigger the event.

Do they need to listen to a different event, or does Adyen need to save the order differently so that it triggers the event like it did before this update? I think more extensions are missing the event, so I would guess the second, but I'd like to hear your opinion.

Thanks!

**Comment by rikterbeek** [comment]
Hi @mrdevries,

I have no idea what event they are listening to. The only thing we have added is setting a state besides the status. What state do they need the order to be in and what event is it looking at ?

Regards,
Rik
Adyen

**Comment by mrdevries** [comment]
Hi @rikterbeek,

The extension listens to the following events:

- sales_order_place_after
- sales_order_save_after
- sales_order_save_commit_after

The comment history of an order goes like this:

1. Order creation. State: pending_payment, status: Wachtend op Bankoverschrijving (it's an iDEAL payment).
2. The comment with "authResult: AUTHORISED". State and status are the same (but no state is showing in the comment history).
3. Then after the cron gets called, the comment with "eventCode: AUTHORISATION". State and status are the same: pending_payment.
4. At the same time, a comment with "Adyen Payment Successfully completed". State: processing, status: Bezig met verwerken.

Comments 1 and 2 are observed by the extension, comments 3 and 4 are not. Hope this helps.

Regards,

Marco de Vries

**Comment by rikterbeek** [comment]
Hi @mrdevries,

Why is  comments 4 not picked up by that observer ? The order->save() is called see:
https://github.com/Adyen/magento/blob/develop/app/code/community/Adyen/Payment/Model/ProcessNotification.php#L1155-L1173

Did you already talk with ActiveAnts why orders are not picked up ?

Regards,
Rik
Adyen

**Comment by seblepers** [comment]
Hi @rikterbeek,

I think that the way you added `setState()` on orders in several places is messing up the states/statuses.
In many places, state and status are not related so the order has a state incompatible with its new status.
One example is in `Adyen_Payment_Model_ProcessNotification`, `_setPrePaymentAuthorized` method:
```php
    private function _setPrePaymentAuthorized($order)
    {
        $status = $this->_getConfigData('payment_pre_authorized', 'adyen_abstract', $order->getStoreId());

        // only do this if status in configuration is set
        if(!empty($status)) {
            $order->addStatusHistoryComment(Mage::helper('adyen')->__('Payment is pre authorised waiting for capture'), $status);
            $order->sendOrderUpdateEmail((bool) $this->_getConfigData('send_update_mail', 'adyen_abstract', $order->getStoreId()));
            // update the state to pending_payment
            $order->setState(Mage_Sales_Model_Order::STATE_PENDING_PAYMENT);

            /**
             * save the order this is needed for older magento version so that status is not reverted to state NEW
             */
            $order->save();
            $this->_debugData[$this->_count]['_setPrePaymentAuthorized'] = 'Order status is changed to Pre-authorised status, status is ' . $status;
        } else {
            $this->_debugData[$this->_count]['_setPrePaymentAuthorized'] = 'No pre-authorised status is used so ignore';
        }
    }
```
The status is retrieved from "Order status: payment authorisation" configuration, which is the list of statuses assigned to 2 states: `new` and `processing`.
Cf. `app/code/community/Adyen/Payment/etc/system.xml` file:
```xml
<source_model>adminhtml/system_config_source_order_status_newprocessing</source_model>
```
But in `_setPrePaymentAuthorized` method, the order is set with state `pending_payment` (`Mage_Sales_Model_Order::STATE_PENDING_PAYMENT`).

This is a problem when an administrator manually adds a comment to the order in BO, because the order will be saved with the default status assigned to `pending_payment` state.
Example here, the order has `processing` status but `pending_payment` state:
![image](https://cloud.githubusercontent.com/assets/621304/22075132/11f66792-ddab-11e6-8e32-996abfee06de.png)

Another problem can occur when using API and/or Web Services.

IMHO, you should apply the state which the configured status is assigned to.
For example, if "Order status: payment authorisation" configuration si set to a status assigned to `processing` state, you should set order's state to `processing` value.

**Comment by seansan** [comment]
@seblepers Is this still an issue?

**Comment by rikterbeek** [comment]
Hi @seblepers,

This should be resolve in the latest releases. Feel free to open a new issue if there are still issues.

Regards,
Rik
Adyen
