### ISSUE TITLE
Unintended session start with API call on every Magento page request

### ISSUE THREAD

**Issue by IvanChepurnyi** [Adyen/adyen-magento#652]
Adyen Directory API gets hit by Magento on every request if curl requests is failing.  Situation at least should be considered a misconfigured instance and get cached unless adyen configuration gets changed. In general the module adds around 200ms to every dynamic page of Magento.

Another side effect of it is that module starts sessions for requests that do not need it, it also adds unexpected behavior to Magento instances that need session free request to serve pure light responses. With Adyen extension installed it is impossible, as it always starts session, even when NO_START_SESSION flag is set in controller action. 

This event definition is triggering a problem:

``` xml
              <controller_action_predispatch>
                <observers>
                    <adyen_payment_hpp>
                        <class>adyen/observer</class>
                        <method>addMethodsToConfig</method>
                    </adyen_payment_hpp>
                    <adyen_payment_billing_agreement>
                        <class>adyen/billing_agreement_observer</class>
                        <method>addMethodsToConfig</method>
                    </adyen_payment_billing_agreement>
                </observers>
            </controller_action_predispatch>
```

At least Adyen module could use `controller_action_predispatch_checkout` and cache failed API  response from time to time. 

In general, I would advise refactoring this kind of configuration in memory extension to a different event, like the first quote load process. Also creating a local proxy table of available payment methods per store with automatic sync by cron per store is a better option than hitting API all the time.

**Comment by rikterbeek** [comment]
Hi @IvanChepurnyi,

Thanks for your reply, I understand your issue. Adyen HPP should always be correctly configured so 
maybe we need to throw an exception when result is empty. Caching a non result is not ideal because the problem is that the payment method is not correct configured. I will look into using the controller_action_predispatch_checkout instead so it is not triggered for all page calls.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @IvanChepurnyi,

The controller_action_predispatch_checkout would be possible for the front-end but for backend orders it will not work. For the adminhtml we could use the adminhtml_controller_action_predispatch_start event what do you think ? Doing the calls through a cronjob is difficult because the result will be variable based on currency/amount of the basket.

Regards,
Rik
