### ISSUE TITLE
Please add Ideal QR code as new payment method

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/adyen-magento#688]
Hi, can we add the new ideal QR code as a payment option? 

I just saw it working with Multi Safe Pay: https://www.ideal.nl/ontvangen/aan-de-slag/qr-code/

and a good example can be found here: megekko.nl

this is supposed to really increase conversion, also for mobile

also see the attachments (see under bancontact)

![betaalmethode](https://cloud.githubusercontent.com/assets/11224809/19727156/89b9db2e-9b8e-11e6-89b3-8b27c4b2a6d8.PNG)

![ideal_qr](https://cloud.githubusercontent.com/assets/11224809/19727155/885d6a8e-9b8e-11e6-84b2-33f267f08e43.PNG)

**Comment by rikterbeek** [comment]
Hi @shirtsofholl,

Our platform does not support this at this moment. I talked to our internal team and it is not an easy implementation and at the moment we do not have a good business case to implement this into our core system. When it is implemented it will be automatically shown in Magento through the Directory Lookup feature that we have implemented so there is no need for code changes in our extension. I close this issue because it is not requiring any code changes in our code of the extension. If you have any other questions regarding this you can contact us on support@adyen.com.

Regards,
Rik
Adyen
