### ISSUE TITLE
Can we improve this error message?

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#707]
Can we improve this error message?

Clients email us asking what is wrong here. They dont know what to do. Payment was amex.

Request: improve error message to the customer. What happened? Why? How can they solve it?

https://msdn.microsoft.com/en-us/library/windows/desktop/ms679325(v=vs.85).aspx

![image](https://cloud.githubusercontent.com/assets/652395/20883089/8aa97e5c-bae4-11e6-90a2-9a15064ef205.png)

**Comment by shanelja** [comment]
This error is being generated in `Adyen_Payment_Model_Adyen_Abstract::_processResponse` on lines 525-529. This code is triggered only under the following circumstances:

 - `paymentResult` has no `refusalReason` attribute.
 - `refusalReason` does not match any of the refusalReasons matched in the switch statement

There's not much we can do about the use case on line 529 (no refusalReason) since we don't know why the Adyen platform refused the transaction, however, in cases where a refusalReason is supplied which isn't currently supported by this switch statement, we can refer to the API documentation: https://docs.adyen.com/developers/api-manual (under the heading `Authorisation refusal reasons`).

Currently, the following refusalReasons are supported:

 - `Transaction Not Permitted`
 - `CVC Declined`
 - `Restricted Card`
 - `803 PaymentDetail not found`

It seem pertinent to me that we add support for the following reasons as well:

 - `Acquirer Fraud`: `The payment is refused because of suspected acquirer fraud.`
 - `3d-secure: Authentication failed`: `The payment is refused because 3D Secure authentication was not executed or it did not execute successfully.`
 - `Blocked Card`: `The payment is refused because the card used for the transaction is blocked, therefore unusable.`
 - `Cancelled`: `The payment is refused because the transaction is canceled`
 - `Refused`: `The payment is refused`
 - `Declined Non Generic`: `The payment is refused because of an unknown error, please see the documentation for Declined Non Generic`
 - `Acquirer Error`: `The payment is refused because of an error that occurred on the acquirer's end`
 - `Expired Card`: `The payment is refused because the card used for the transaction has expired, therefore it is unusable.`
 - `FRAUD`: `The payment is refused because of suspected fraud`
 - `FRAUD-CANCELLED`: `The payment is refused because the risk check flagged the transaction as fraudulent`
 - `Invalid Amount`: `The payment is refused because an amount mismatch occurred during the transaction process`
 - `Invalid Card Number`: `The payment is refused because the specified card number is incorrect or invalid`
 - `Invalid Pin`: `The payment is refused because the specified PIN number is incorrect or invalid`
 - `Issuer Suspected Fraud`: `The payment is refused because the issuer reported the transaction as suspected fraud`
 - `Issuer Unavailable`: `The payment is refused because it is not possible to contact the shopper’s bank to authorise the transaction`
 - `Not enough balance`: `The payment is refused because the card does not have enough money to cover the payable amount`
 - `Not Submitted`: `The payment is refused because the transaction was not submitted correctly for processing`
 - `Not supported`: `The payment is refused because the shopper's bank does not support or does not allow this type of transaction`
 - `Pending`: `The payment is refused because the transaction is in between states, and it is waiting for its current state to be replaced with the new, pending one`
 - `Pin tries exceeded`: `The payment is refused because the shopper specified an incorrect PIN number more that three times in a row`
 - `Pin validation not possible`: `The payment is refused because it is not possible to validate the specified PIN number`
 - `Referral`: `The payment is refused because of a referral error`
 - `Revocation Of Auth`: `The payment is refused because the shopper requested to stop a subscription`
 - `Shopper Cancelled`: `The payment is refused because the shopper cancelled the transaction before completing it`
 - `Withdrawal count exceeded`: `The payment is refused because the number of withdrawals permitted for the shopper's card have exceeded`
 - `Withdrawal amount exceeded`: `The payment is refused because the withdrawal amount permitted for the shopper's card has exceeded`
 - `Transaction Not Permitted`: `The payment is refused because of a permission error, please see the documentation for Transaction Not Permitted`
 - `Unknown`: `The payment is refused because of an unknown error, please contact the Adyen support team at support@adyen.com to request assistance`

We'll need translations for these adding to the following locale files:

 - `app/locale/de_DE/Adyen_Payment.csv`
 - `app/locale/es_ES/Adyen_Payment.csv`
 - `app/locale/fr_FR/Adyen_Payment.csv`
 - `app/locale/nl_NL/Adyen_Payment.csv`
 - `app/locale/pt_BR/Adyen_Payment.csv`

It's probably not a bad idea to change from a switch statement to an array, either, since it'll clean the code up somewhat. Thoughts on this, @seansan?

**Comment by seansan** [comment]
I think this is spot on.

And knowing (maybe logging for a while) the most common refusal methods
will also help. As I understand there a are many.  Also a quick win could
already be is to insetad of showing the generic version (in case 2: no
refusal reason in switch statement) that we at least see the code between
brackets, say "Payment has been DECLINED (reason: <code here>)": at least
that will help customer support on our end to help the customer

**Comment by shanelja** [comment]
Since the end goal of this for you @seansan seems to be fronte-nd error printing, I think there may be some concerns about leaking customer card information (such as that a customer doesn't have enough cash, etc) perhaps a more generic message would be best for the following error responses:

 - `Invalid Pin`
 - `Not enough balance`
 - `Withdrawal count exceeded`
 - `Withdrawal amount exceeded`

Maybe something along the lines of: `The payment is refused because of an issue with the specified card`

**Comment by rikterbeek** [comment]
Hi All,

You do not want to provide a specific reason to provide to the customer for a security perspective.
I think we already cover the basics. The error message you addresses can be changed to anything you want by translation in Magento.

Regards,
Rik
Adyen

**Comment by shanelja** [comment]
@rikterbeek agreed, I mentioned that in the comment above yours. I do think it is worth, however, talking about expanding the ones we currently support.

Would adding the following pose any security issues? :

 - `Cancelled`  
 - `Shopper Cancelled`  
 - `Issuer Unavailable`  
 - `Acquirer Error`  
 - `Not Submitted`  
 - `Unknown`

**Comment by seansan** [comment]
Lets dont create a security risk everywhere that does not exist

Giving detailed enough feedback to the user that is currently doing the
payment is important

A wrong Cvc should message = cvc error

And not something went wrong but we are not telling you what

**Comment by rikterbeek** [comment]
This is now the case.

Regards,
Rik
Adyen
