### ISSUE TITLE
Adyen POS result "canceled", but the order turns to "Processing" afterwards. 

### ISSUE THREAD

**Issue by crossgate9** [Adyen/adyen-magento#719]
Dear, 

We have a weird issue for POS payment. 

It happened once when we paid by credit card on POS, but somehow the transaction failed (maybe WiFi signal is not good enough). 

But when we look into the order information in Magento backend, the order status is cancelled at first, but after next notification, it turns to processing. 

Below please find the status history: 
<pre>
Dec 22, 2016 9:05:46 AM|Pending
Customer Notified  
</pre>
<pre>
Dec 22, 2016 9:06:15 AM|Canceled
Customer Not Notified 
Adyen App Result URL Notification: 
Result: ERROR 
paymentMethod: POS
</pre>
<pre>
Dec 22, 2016 9:07:01 AM|Canceled
Customer Not Notified 
Adyen HTTP Notification(s): 
eventCode: AUTHORISATION 
pspReference: ******************
paymentMethod: visa 
success: true 
reason:133729:8065:07/2020 
amount value: 3490
</pre>
<pre>
Dec 22, 2016 9:07:01 AM|Processing
Customer Not Notified 
Payment is pre authorised waiting for capture
</pre>
<pre>
Dec 22, 2016 9:07:02 AM|Processing
Customer Not Notified 
Adyen Payment Successfully completed
</pre>
Best Regards,
Allen

**Comment by rikterbeek** [comment]
Hi @crossgate9,

We have seen this before and almost every time this is because of a bad WIFI connection. If you want us to look into this transaction please send the adyen_result_pos.log to magento@adyen.com together with your merchantAccount and serial number of the POS device.

Regards,
Rik
Adyen

**Comment by crossgate9** [comment]
We are testing the POS device and hope to put it in the shop with big screen tablets. 
If we can assure good WiFi connection, we haven't suffered the problem till now. 
Thanks a lot @rikterbeek . 

BTW, Will it be a fix in the coming future? or is that possible to notify via email once it happens.

**Comment by rikterbeek** [comment]
Hi @crossgate9,

It is difficult to make fixes if internet connection just disconnects during a transaction. We are trying to make this as clear to the merchant/shopper if the payment was successful or not. But important thing is to have internet connection always available. We will continuously fix this edge case scenarios in the upcoming releases of our apps and libraries. Please check the release notes of the app to see what has been changed. Good to hear that the problem is resolved if the connection is up.

Regards,
Rik
Adyen
