### ISSUE TITLE
Credit Card signature error after upgrading to 2.8.1

### ISSUE THREAD

**Issue by sandermangel** [Adyen/adyen-magento#721]
I received errors on the CC signature after upgrading to 2.8.1. I think `adyen/payment/adyen.encrypt_0_1_16.js` was missing because after including they were gone.

Created a PR: https://github.com/Adyen/adyen-magento/pull/720

**Comment by rikterbeek** [comment]
Hi @sandermangel,

We include the script inside the template because of support for all browsers.
The templates are using the new adyen.encrypt_0_1_18.js version of the lib.
see: https://github.com/Adyen/adyen-magento/blob/develop/app/design/frontend/base/default/template/adyen/form/cc.phtml#L348

Can you check why this is not loaded in your checkout ?

Regards,
Rik
Adyen

**Comment by sandermangel** [comment]
@rikterbeek couldn't find a particular reason why it's not loaded. Might be some JavaScript error or conflict in some different part. Whats the reason for including the JavaScript file this way and not the traditional Layout XML way?

**Comment by rikterbeek** [comment]
@sandermangel This is needed for support for all browsers. We have seen adding it into the header will cause issues for IE8.

Regards,
Rik
Adyen
