### ISSUE TITLE
Version 2.8.1 Exception: Error during unserialization in public_html/lib/Unserialize/Parser.php:60

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#723]
Version 2.8.1 Exception: Error during unserialization in public_html/lib/Unserialize/Parser.php:60

Exception: Error during unserialization in public_html/lib/Unserialize/Parser.php:60
Stack trace:
#0 public_html/app/code/core/Mage/Core/Helper/UnserializeArray.php(44): Unserialize_Parser->unserialize(Object(Mage_Core_Model_Config_Element))
#1 public_html/app/code/core/Mage/Adminhtml/Model/System/Config/Backend/Serialized.php(37): Mage_Core_Helper_UnserializeArray->unserialize(Object(Mage_Core_Model_Config_Element))
#2 public_html/app/code/core/Mage/Core/Model/Config/Data.php(78): Mage_Adminhtml_Model_System_Config_Backend_Serialized->_afterLoad()
#3 public_html/.modman/magento-configscopehints/app/code/community/EW/ConfigScopeHints/Block/Adminhtml/System/Config/Form.php(87): Mage_Core_Model_Config_Data->afterLoad()
#4 public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): EW_ConfigScopeHints_Block_Adminhtml_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#5 public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#6 public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#7 public_html/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#8 public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->editAction()
#9 public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#12 public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#13 public_html/index.php(83): Mage::run('soh_nl', 'store')
#14 {main}

**Comment by shanelja** [comment]
Hi @seansan, this error appears to be completely unrelated to the Adyen-magento project, unless I'm missing something. I would try creating an issue on the https://github.com/ericthehacker/magento-configscopehints project, since the EW_ConfigScopeHints seems to be responsible for this issue, based on `EW_ConfigScopeHints_Block_Adminhtml_System_Config_Form->initFields` being the first none-core code path to be executed and everything after that being either part of the EW module or the Magento core.

Unfortunately, that module looks to be unmaintained (the last commit was over a year ago, and there hasn't been contributor activity since March 6) so if there is an issue with it, you will likely have to fork the module code.

**Comment by rikterbeek** [comment]
@shanelja thanks for your in-depth responds!

**Comment by sandermangel** [comment]
Hi @seansan, we've used https://github.com/avstudnitz/AvS_ScopeHint on several projects with no issues. might work for you as well
