### ISSUE TITLE
protected function _getPaymentData($key = null) // /public_html/app/code/community/Adyen/Payment/Block/Form/Abstract.php on line 77

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#724]
Using this version: https://github.com/Adyen/adyen-magento/releases/tag/2.8.1

Still see notice in error logs

Seems try does not work on unserialize

do we know why this error occurs anyways? (the wrong offset I mean)

Notice: unserialize(): Error at offset 0 of 4 bytes  in /public_html/app/code/community/Adyen/Payment/Block/Form/Abstract.php on line 77

    protected function _getPaymentData($key = null)
    {
        if (is_null($this->_paymentData)) {
            $payment = $this->_getQuote()->getPayment();

            if($payment->getPoNumber()) {
                try {
                    $this->_paymentData = unserialize($payment->getPoNumber());
                } catch (Exception $e) {
                    $this->_paymentData = array();
                }
            }
        }

**Comment by shanelja** [comment]
This is because unserialize doesn't throw exceptions on failure and instead returns `false` and throws an `E_NOTICE` warning. The simplest fix for the problem would likely be sticking an `@` in front of the unserialize function. In an isolated scenario, we would add a custom error handler to convert the `E_NOTICE` to an `ErrorException`, but since the module needs to play nicely with other user's code, I would suggest we replace this method with:

```
protected function _getPaymentData($key = null)
{
    if (is_null($this->_paymentData)) {
        $payment = $this->_getQuote()->getPayment();

        if($payment->getPoNumber()) {
            try {
                $paymentData = @unserialize($payment->getPoNumber());
                $this->_paymentData = $paymentData ? $paymentData : array();
            } catch (Exception $e) {
                $this->_paymentData = array();
            }
        }
    }
```

We still need to provide the `try` block, because it can catch downstream errors in the `getData` method call invoked by `$payment->getPoNumber()`

**Comment by rikterbeek** [comment]
Hi @shanelja,

Thanks for your contribution looks good but I think the best approuch is to switch to save the fields not as serialized data into the PoNumber but into the additionalData field as seperate fields. Then we do not need to serialize and desiseriale the data.

Regards,
Rik
Adyen
