### ISSUE TITLE
Reason for PHP 5.6 composer requirement

### ISSUE THREAD

**Issue by tr33m4n** [Adyen/adyen-magento#762]
Hi there,

Just trying to figure out what requires PHP 5.6 in the 2.9 branch of this module? I've had to mirror and knock the dependency down the 5.5 and not seen any issues currently

Cheers

**Comment by rikterbeek** [comment]
Hi @tr33m4n,

The PHP 5.5 version is not supported by PHP anymore see: http://php.net/supported-versions.php
It could be that it is working in older versions but I highly recommend to use a supported version.

Regards,

**Comment by tr33m4n** [comment]
@rikterbeek That was what I thought, just wondering whether there was anything in the code base that required 5.6. Thanks for the help

Cheers

**Comment by rikterbeek** [comment]
Hi @tr33m4n,

No problem any reason why you are not upgrading to 5.6 ?

Regards,
Rik
Adyen

**Comment by RJacksonm1** [comment]
I'd just like to jump in and point out that whilst PHP versions below 5.6 are no longer receiving security fixes directly from PHP, some of those versions do have continued support from certain Linux distributions.  Debian and Ubuntu's LTS releases, for example, are running PHP 5.4.45 / 5.5.9 with ongoing support until May 2018 / April 2019.

There will be developers in the wild whom, for various technical and/or bureaucratic reasons, don't have control over their hosting environment and/or can't upgrade to PHP 5.6, and thus can't upgrade `adyen/payment`, despite their operating system & PHP package technically still being supported. This is a major sticking point given customers **must** upgrade to the latest release of this package 2.9.0 for continued Mastercard support.

I understand and agree with dropping support for outdated PHP versions, but in this case I think the limit should've been set a little lower; PHP 5.4 is the earliest version of PHP I can see with ongoing, albeit third-party, support.

**Comment by rikterbeek** [comment]
I understand your issue but till now we only heard the problem here by two persons and the rest of our merchants are fine with this. We believe it is still the best thing to use PHP versions that are supported by PHP itself.

Regards,
Rik
Adyen

**Comment by RJacksonm1** [comment]
@rikterbeek 

With all due respect, I don't think Adyen's idea of what's best should dictate my tech stack. My problem is Adyen unnecessarily restricting the environment in which this plugin runs, in contradiction to the claim of what your plugin is compatible with:

>The plugin supports the Magento Community (version 1.8 and higher) and Enterprise edition (version 1.13 and higher).

I can only find information on [CE 1.9+](http://docs.magento.com/m1/ce/user_guide/magento/system-requirements.html) and [EE 1.14+](http://docs.magento.com/m1/ee/user_guide/magento/system-requirements.html), but those versions of Magento require a minimum PHP version of 5.4 and 5.5 respectively.

Although PHP 5.4 and 5.5 is unsupported by PHP themselves, its supported by the latest Magento 1.x release, and it has ongoing security support by Linux distribution maintainers – as my previous comment explains.

If you have a technical reason for requiring PHP 5.6 and above, then that's fair enough – I'll concede my argument if that's the case.

But as far as I can tell, which this discussion hasn't shed any light on, there is no technical argument for the constraint; you guys just decided one day to require PHP 5.6 one day, and you have put the onus on your customers to work around that.

For our projects, we don't want to be in a position where we're running outdated code. We also don't want to upgrade our production runtime environment on a whim, because that's a high risk change. We're working around this by maintaining a private fork of this plugin with the version constraint removed – and that's running just fine on PHP 5.5.

If we accept the realities of our industry, however, surely you recognise that you are putting your customers in a position where they'll just continue running an outdated Adyen plugin, because that is both the path of least resistance, and least risk to their site overall. Is that what you want your cusotmers to be doing?
