### ISSUE TITLE
What is the advised process of "editing" an order with Adyen; payment ref link lost

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#767]
What is the advised process of "editing" an order with Adyen? One cannot just edit an order. And Magento likes us to go through the flow again .... but this is leading to unneccesary problems. 

**Situation**
Customer orders X + Y
Payment is made and confirmed/status new
Emails 1 sec later: can I change Y to Z
Or X is wrong size, can I change
As a result the order needs to be changed: and we credit note order 1, and create the (almost same) order 2

**Business problems**
1) Time/effort of credit note, re-order, save etc .... having 2 orders instead of 1
2)  Loosing the original payment psp ref link to Adyen

If a customer has the above. We ship order 2 with the adjusted size or altered products ... if the customer then returns this order then the payment link to Adyen is lost and we cannot refund

We do understand Adyen cannot solve everything ;P And this is not our question. 

However the element of keeping the payment link active when processing an RMA is important. And something that is either already tackeled in the extension, or maybe should be considered - as a core process of online retail

Thoughts?

**Comment by shanelja** [comment]
Hi @seansan, as I understand it, Adyen in this instance relies heavily on the underlying Magento functionality, as such, modifications to the `sales_flat_order_items` table will update the items which are processed when a refund is issued from Adyen. You will still have to manually increase and decrease any stock levels which have been updated, but it's a workable solution.

With that being said, I heavily advise against this as you're subverting the functionality of Magento itself, the correct flow is to edit the order in the admin to remove the item you no longer want and to raise a new admin order with the new item on it.

This feels like core Magento functionality and not a function of Adyen's process, since this should be implemented for all payment providers and changes how the admin order process works. I'm not exactly sure how to submit a feature request for Magento 1, but you could always create a module which adds this functionality?

**Comment by seansan** [comment]
>> With that being said, I heavily advise against this as you're subverting
the functionality of Magento itself, the correct flow is to edit the order
in the admin to remove the item you no longer want and to raise a new admin
order with the new item on it.

This flow does not exist in Magento. There is no *edit* functionality

​Hence our question. There is only fully cancel and credit the current
order. And create a new order. The problem is that the "credit" is on the
old order - whilst we are working in a new (2nd order)

Magento has a linking ID in the core for tracking the original order where
it came from ... maybe that can be used​

**Comment by rikterbeek** [comment]
Hi @seansan,

I understand your issue but I think this is some functionality you need to build into Magento because they do not offer this kind of scenario. Creating some logic for this could be very specific to the needs of the customer and I do not see a generic solution and business case for building this into our extension. If your business is really demanding this issue to be solved you should ask your developer or integration partner to build some custom logic to solve your issue.

Regards,
Rik
Adyen
