### ISSUE TITLE
Limit on processing the notification queue

### ISSUE THREAD

**Issue by sandermangel** [Adyen/adyen-magento#787]
https://github.com/Adyen/adyen-magento/blob/develop/app/code/community/Adyen/Payment/Model/ProcessNotification.php#L1521

Whys is there a date limit on this collection? 
We had issues this weekend where the cronjob didn't run for about 20 hours leaving some notifications to never be processed. Curious what the thought behind the limit it.

**Comment by rikterbeek** [comment]
Hi @sandermangel,

We add a limit that the notification needs to be older then 1 minute because some merchants see that order saving cost a bit more time. We put it on one day because we presume the notification cronjob is  always running could scale this up to more days if needed. Was the one day the issue ?

Regards,

**Comment by sandermangel** [comment]
Hi @rikterbeek 

That seems to be the issue indeed

**Comment by rikterbeek** [comment]
Hi @sandermangel,

Closing this issue right now. Let me know if you want it to be delayed to more days.

Regards,
Rik
Adyen
