### ISSUE TITLE
modman file

### ISSUE THREAD

**Issue by simonemonterubbiano** [Adyen/adyen-magento#825]
Hi,
I noticed that in 2.9.2 versione the modman file has no more "*" in all paths and this creates compatibility problems with others modules.
Can you revert modman file as in 2.9.1 version?
For example:

2.9.1 (correct)
app/code/community/Adyen/*                      app/code/community/Adyen/

2.9.2 (wrong)
app/code/community/Adyen/                       app/code/community/Adyen/

Thank you

**Comment by rikterbeek** [comment]
Hi @dropadmin,

Thanks for letting us know. This has been changed becuase of this:

The problem here is that if you leave it as it is, and after you have installed the latest patch on your magento installation, since the composer strategy is changed to copy, the mapping is completely wrong. So every time I do a composer install, I see Adyen/Payment/Fee/Fee. Then again  Adyen/Payment/Fee/Fee/Fee and on and on. This needs to fixed and released because can cause major problems.

@cstergianos could you let us know in more details I remember you said that this was a big issue with the previous modman file.

Regards,
Rik
Adyen

**Comment by cstergianos** [comment]
@rikterbeek what kind of problems are you experiencing? Currently we use Adyen module with the latest changed modman file and we have no issues at all. The "/*" in the end is not a good syntax to use. But it is possible that the start character was not the problem but the gaps and spaces after this.

**Comment by dropadmin** [comment]
Hi @rikterbeek 
if I run "composer install" or "composer update", it creates symlinks of app/design/adminhtml/default/default/layout/ (for example) so I lost all Magento files into this folder.
This happens also for all other folders:

app/design/adminhtml/default/default/template/
app/design/frontend/base/default/layout/
app/design/frontend/base/default/template/
...
...

I think the best way is using the "*" symbol, or using the full path, for example:

app/design/adminhtml/default/default/layout/adyen.xml
app/design/adminhtml/default/default/layout/adyen_fee.xml

On composer.json I use:
"magento-deploystrategy": "symlink",

Regards,
Simone

**Comment by cstergianos** [comment]
@dropadmin that is why! You should not use the symlink strategy! It has really big security issues that are solved in the SUPEE-9767 magento patch. Apply the patch and then this will work. Magento itself suggested to apply the patch asap.

**Comment by dropadmin** [comment]
@cstergianos I'm using the latest Magento version (Vers. Magento 1.9.3.4).
I enabled symlink on Magento from database, because on the latest versione there is no choice on backoffice.
We enbled cli only from shell (ssh) and not from web, so symlink are secure.

I think the copy or symlink strategy is not the problem, but the modman file syntax. 
I think the best way to write the modman file is using the full path of each file. (see https://github.com/colinmollenhour/modman/wiki/Tutorial)

**Comment by cstergianos** [comment]
@dropadmin I agree but is a lot of work. But please do not add more than one space between the 2 paths and no asterisks, because I am facing really big issues.

**Comment by JeroenBoersma** [comment]
Latest 2.9.3 also breaks Magento stores: https://github.com/Adyen/adyen-magento/commit/b91c8623298239a30e76cad157c112c3c5ac4dd4#commitcomment-24881810

mapping shell -> magedir/shell is not the best idea
One should only link module specific directories...

PR coming up

**Comment by cstergianos** [comment]
@JeroenBoersma nice one! Although I did not have any problems locally, makes sense that it can break.

**Comment by cstergianos** [comment]
@rikterbeek @JeroenBoersma  Hello again!
I know it is 2 years later but we are still facing the same issue as you can see [here](https://photos.app.goo.gl/37xoYuuHNjUb6bin6).

Would 'nt be better to just delete the modman file and do all the mapping within composer.json?
