### ISSUE TITLE
Front-end validation for creditcard fields

### ISSUE THREAD

**Issue by TomFranssen** [Adyen/adyen-magento#955]
**Magento version**: 1.14.3.10
**Plugin version**: 2.12.0
**Description**
I have implemented the new Adyen Payment 2.12.0 plugin with the new Secured Fields functionality.
I have styled the new iframe inputs (creditcard name, creditcard number, creditcard expiration date, creditcard cvc) to match our design. When I try to fill in all the fields except the new secured iframe fields I can submit the form. I don't get any frontend validation when I don't fill in the fields. Am I doing something wrong or is front-end validation not present in the current implementation?

**Comment by Aleffio** [comment]
Hi @TomFranssen ,
There is validation on the card type, securedFields return a card type when the number is filled in, we check if this card is allowed in Magento, if not, we show an "Invalid card type" alert.
We will add validation to the other fields, since at the moment the only check is on the credit card number.

**Comment by TomFranssen** [comment]
It would also be nice if it's possible to make the fields required. Because now when you don't enter anything you can still submit the form without any values.

**Comment by rikterbeek** [comment]
Hi @TomFranssen,

With the latest release this should be the case. Feel free to open a new issue if you still have an issue.

Regards,
Rik
Adyen
